---
language: python
python: "2.7"
services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-pip
  - docker run -d --hostname rabbit --name rabbit-mgmt -P rabbitmq:3-management

install:
  - pip install ansible==2.3.2.0

script:
  - cd tests && ansible-playbook -i localhost, test.yml

after_success:
    - echo "Success"