---
language: python
python: "2.7"
#services:
#  - docker

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-pip

install:
  - pip install ansible==2.3.2.0

script:
    - echo "test"

after_success:
    - echo "Success"