---
language: python
python: "2.7"
services:
  - docker

env:
  - ANSIBLE_VERSION=2.3.2.0
  - ANSIBLE_VERSION=2.4.0.0 

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-pip
  - docker run -d --hostname rabbit --name rabbit-mgmt -p 15672:15672 rabbitmq:3-management

install:
  - pip install ansible==$ANSIBLE_VERSION

script:
  - cd tests && ansible-playbook -i localhost, play.yml -e @vars_1.yml
  - docker exec rabbit-mgmt rabbitmqctl list_queues | egrep -v "^amq\." | wc -l | egrep "^\s*2$"
  - docker exec rabbit-mgmt rabbitmqctl list_exchanges | egrep "some_exchange\s+direct"
  - docker exec rabbit-mgmt rabbitmqctl list_queues | egrep "label.deleted\s+"
  - docker exec rabbit-mgmt rabbitmqctl list_queues |  wc -l | egrep "^\s*2$"
  - docker exec rabbit-mgmt rabbitmqctl list_bindings | egrep "some_exchange\s+exchange\s+label\.deleted\s+queue\s+\*\.labels\.deleted"
  - docker exec rabbit-mgmt rabbitmqctl list_bindings | egrep "some_exchange\s+exchange\s+label\.deleted\s+queue\s+us\.\*"
  - docker exec rabbit-mgmt rabbitmqctl list_bindings |  wc -l | egrep "^\s*3$"
  - cd tests && ansible-playbook -i localhost, play.yml -e @vars_2.yml
  - docker exec rabbit-mgmt rabbitmqctl list_bindings |  wc -l | egrep "^\s*1$"
  - cd tests && ansible-playbook -i localhost, play.yml -e @vars_3.yml
  - docker exec rabbit-mgmt rabbitmqctl list_queues | egrep -v "^amq\." | wc -l | egrep "^\s*1$"

after_success:
    - echo "Success"